package com.oliver.siloker.domain.error

enum class NetworkError : BaseError {
    SERVER_ERROR,
    BAD_REQUEST,
    NO_INTERNET,
    UNAUTHORIZED,
    PAYMENT_REQUIRED,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ANSWERED,
    NOT_ACCEPTABLE,
    PROXY_AUTHENTICATION_REQUIRED,
    REQUEST_TIMEOUT,
    CONFLICT,
    GONE,
    LENGTH_REQUIRED,
    PRECONDITION_FAILED,
    PAYLOAD_TOO_LARGE,
    URI_TOO_LONG,
    UNSUPPORTED_MEDIA_TYPE,
    RANGE_NOT_SATISFIABLE,
    EXPECTATION_FAILED,
    MISDIRECTED_REQUEST,
    TOO_MANY_REQUEST,
    UNKNOWN
}